---

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install nagios, nrpe, xinetd, and nrpe-plugins
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nagios
    - nrpe
    - xinetd
    - nagios-plugins-all
    - nagios-selinux

- name: add NRPE to services
  lineinfile:
    path: /etc/services
    regexp: '^nrpe'
    line: "nrpe            {{ nrpe_port }}/tcp"
    state: present

- name: add nrpe config for xinetd
  template:
    src: nrpe.j2
    dest: /etc/xinetd.d/nrpe
    owner: root
    group: root
    mode: 0600
  notify:
    - restart xinetd

- name: allow http via firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: enable services
  systemd:
    name: xinetd
    state: started
    enabled: True
  with_items:
    - httpd
    - nagios
    - xinetd

...